// File generated by FlutterFire CLI & NearTalk setup.
// To connect your own Firebase project, run: `flutterfire configure`
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhcodV_gkDFGod2idFIdZVuSzmvK4318k',
    appId: '1:628046425856:web:c421c981dc27f3749e8de5',
    messagingSenderId: '628046425856',
    projectId: 'neartalk-app-2433c',
    authDomain: 'neartalk-app-2433c.firebaseapp.com',
    storageBucket: 'neartalk-app-2433c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhcodV_gkDFGod2idFIdZVuSzmvK4318k',
    appId: '1:628046425856:android:c421c981dc27f3749e8de5',
    messagingSenderId: '628046425856',
    projectId: 'neartalk-app-2433c',
    storageBucket: 'neartalk-app-2433c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhcodV_gkDFGod2idFIdZVuSzmvK4318k',
    appId: '1:628046425856:ios:c421c981dc27f3749e8de5',
    messagingSenderId: '628046425856',
    projectId: 'neartalk-app-2433c',
    storageBucket: 'neartalk-app-2433c.firebasestorage.app',
    iosBundleId: 'com.neartalk.app.neartalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhcodV_gkDFGod2idFIdZVuSzmvK4318k',
    appId: '1:628046425856:web:c421c981dc27f3749e8de5',
    messagingSenderId: '628046425856',
    projectId: 'neartalk-app-2433c',
    authDomain: 'neartalk-app-2433c.firebaseapp.com',
    storageBucket: 'neartalk-app-2433c.firebasestorage.app',
  );
}
